[.text-justify]
= Slexamplus
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
// Docinfo is used for foldable TOC.
// -> For full usage example see https://github.com/remkop/picocli
:docinfo: shared,private
:linkcss:
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css

== Overview

_Slexamplus_ (the name stands for +"+*Sl*+ing"+ and +"+*exampl*+e"+) is an example application for the https://github.com/ciechanowiec/sling_rocket[Sling Rocket] framework. It demonstrates various features that a business application for Sling Rocket can utilize and can serve as a template for similar applications. Among others, the features presented in _Slexamplus_ include:

[upperalpha]
. Packaging a business application into a single deployable artifact.
. Deploying content to the `/apps` path in JCR.
. Java logic:
[upperroman]
.. OSGi unary and factory configurations.
.. Dynamic OSGi service relationships.
.. Accessing JCR via `eu.ciechanowiec.sling.rocket.commons.ResourceAccess`.
.. Read-write operations on JCR using the Apache Sling API and JCR API.
.. Reading OSGi configuration variables from the environment.
.. Registering servlets by path and resource types.
.. Usage of external dependencies.
.. Performing heavy JCR operations.
.. Rendering HTML pages.
.. Using Sling Models.
.. Integrating static code analysis and test enforcement into the build process.
.. Conducting unit testing, including tests against a real in-memory JCR.
.. Registering JMX MBeans.
. Rendering HTML pages with HTL and Sling Models.
. JCR indexing.
. Repository initialization.
. Deploying OSGi configurations.
. Deploying static content to JCR via a bundle.
. Registering custom node types with the use of a https://developer.adobe.com/experience-manager/reference-materials/spec/jcr/2.0/25_Appendix.html[compact node type definition (CND) file].

== How to Use

Start the Sling Rocket framework:
[source,bash]
----
docker compose up --detach
----

Deploy _Slexamplus_ into the Sling Rocket framework:
[source,bash]
----
mvn clean install -P installAll
----

Deploy only the `bundle` module of _Slexamplus_ into the Sling Rocket framework:
[source,bash]
----
mvn clean install -P installBundle
----

== License
The program is subject to MIT No Attribution License

Copyright © 2024-2025 Herman Ciechanowiec

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.
