[.text-justify]
= Slexamplus
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
:docinfo: shared,private
:linkcss:
:sourcedir: {docdir}
:pdf-theme: {sourcedir}/docs/themes/basic.yml
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css
:!table-caption:
:!figure-caption:

== Overview

++++
<!-- vale off -->
++++
_Slexamplus_ (the name stands for +"+*Sl*+ing"+ and +"+*exampl*+e"+) is an example application for the https://github.com/ciechanowiec/sling_rocket[Sling Rocket] framework. It demonstrates various features that a business application for Sling Rocket can use and can serve as a template for similar applications. Among others, the features presented in _Slexamplus_ include:
++++
<!-- vale on -->
++++

. Packaging a business application into a single deployable artifact.
. Deploying content to the `/apps` path in JCR.
. Java logic:
.. OSGi unary and factory configurations.
.. Dynamic OSGi service relationships.
.. Accessing JCR via `eu.ciechanowiec.sling.rocket.commons.ResourceAccess`.
.. Read-write operations on JCR using the Apache Sling API and JCR API.
.. Reading OSGi configuration variables from the environment.
.. Registering servlets by path and resource types.
.. Usage of external dependencies.
.. Performing heavy JCR operations.
.. Rendering HTML pages.
.. Using Sling Models.
.. Integrating static code analysis and test enforcement into the build process.
.. Conducting unit testing, including tests against a real in-memory JCR.
.. Registering JMX MBeans.
.. Scheduling Sling Jobs.
. Rendering HTML pages with HTL and Sling Models.
. JCR indexing.
. Repository initialization.
. Deploying OSGi configurations.
. Deploying static content to JCR via a bundle.
. Registering custom node types with the use of a https://developer.adobe.com/experience-manager/reference-materials/spec/jcr/2.0/25_Appendix.html[compact node type definition (CND) file].
. HTML form submission.

== How to Use

Start the Sling Rocket framework:
[source,bash]
----
docker compose up --detach
----

Deploy _Slexamplus_ into the Sling Rocket framework:
[source,bash]
----
mvn clean install -P installAll
----

Deploy only the `bundle` module of _Slexamplus_ into the Sling Rocket framework:
[source,bash]
----
mvn clean install -P installBundle
----

== About the Document

This document uses https://asciidoc.org[AsciiDoc^] markup language and resides in the project repository.

=== Export
. To export the document to the supported output formats, install the following tools:
.. https://asciidoctor.org/#installation[Asciidoctor^]
.. https://docs.asciidoctor.org/pdf-converter/latest/install/[Asciidoctor PDF^]
.. https://pandoc.org/installing.html[Pandoc^]
. To export to HTML:
+
[source,bash]
----
asciidoctor --attribute allow-uri-read README.adoc
----
. To export to PDF:
+
[source,bash]
----
asciidoctor-pdf --attribute allow-uri-read --require ./docs/lib/auto-list-style.rb README.adoc
----
. To export to DOCX - Asciidoctor converts the document to DocBook XML, which Pandoc then converts to DOCX:
+
[source,bash]
----
asciidoctor --backend docbook --attribute allow-uri-read --out-file - README.adoc | pandoc --from docbook --to docx --output README.docx
----

=== Linting

==== General Rules
. https://vale.sh[Vale^] lints the document.
. Vale enforces the following style guides:
.. Native https://vale.sh/docs/styles#vale[Vale style^], with https://github.com/vale-cli/en_US-web/tree/master[English dictionary] included.
.. modified https://developers.google.com/style[Google Developer Documentation Style Guide^] via the https://github.com/vale-cli/Google[Google package^]
.. modified https://vale.sh/hub/jdkato/write-good/[write-good linter^] via the https://github.com/vale-cli/write-good[write-good package^]
.. https://github.com/amperser/proselint/[proselint^] via the https://github.com/vale-cli/proselint[proselint package^]
.. custom project rules
. Vale configuration is in `link:.vale.ini[]`.

==== Usage
. Install Vale as described in the https://vale.sh/docs/install/[official documentation].
. Lint the document:
+
[source,bash]
----
vale README.adoc
----

++++
<!-- vale off -->
++++

== License
The program is subject to MIT No Attribution License

Copyright © 2024-2026 Herman Ciechanowiec

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.
