package eu.ciechanowiec.slexamplus;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.servlet.Servlet;
import jakarta.servlet.ServletResponse;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.apache.sling.api.SlingJakartaHttpServletRequest;
import org.apache.sling.api.SlingJakartaHttpServletResponse;
import org.apache.sling.api.request.RequestPathInfo;
import org.apache.sling.api.servlets.HttpConstants;
import org.apache.sling.api.servlets.ServletResolverConstants;
import org.apache.sling.api.servlets.SlingJakartaAllMethodsServlet;
import org.apache.sling.servlets.annotations.SlingServletResourceTypes;
import org.jspecify.annotations.NonNull;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.propertytypes.ServiceDescription;

import java.io.Writer;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

@Component(
    service = {RequestEchoServlet.class, Servlet.class},
    immediate = true
)
@ServiceDescription("POC servlet bound to the default resource type that echoes request info as JSON")
// PMD.UseConcurrentHashMap: the suppressed maps are method-local and never accessed concurrently
@SuppressWarnings({"squid:S1948", "PMD.UseConcurrentHashMap", "PathAnnotation"})
@Slf4j
@SlingServletResourceTypes(
    methods = {HttpConstants.METHOD_GET, HttpConstants.METHOD_POST},
    selectors = "poc",
    extensions = "json",
    resourceTypes = ServletResolverConstants.DEFAULT_RESOURCE_TYPE
)
// The JAX-RS and OpenAPI annotations on this servlet don't drive any runtime behavior
// (routing is defined by @SlingServletResourceTypes above). They only feed
// the build-time OpenAPI documentation generated by swagger-maven-plugin-jakarta.
// The annotated HTTP methods are 'public' instead of 'protected' because the OpenAPI
// annotation reader observes only public methods
@OpenAPIDefinition(
    info = @Info(
        title = "Slexamplus API",
        description = "POC API of the Slexamplus application",
        version = "1.0.0"
    )
)
@Path("/{resourcePath}.poc.json")
public class RequestEchoServlet extends SlingJakartaAllMethodsServlet {

    @SuppressWarnings("VoidMethodAnnotatedWithGET")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(
        summary = "Describe the addressed resource and request",
        description = "Returns a JSON object describing the addressed JCR resource and the HTTP request: "
            + "resource path, selectors, extension, query string and HTTP method",
        parameters = @Parameter(
            name = "resourcePath",
            in = ParameterIn.PATH,
            required = true,
            description = "Path of the addressed JCR resource",
            schema = @Schema(type = "string")
        )
    )
    @ApiResponses(
        @ApiResponse(
            responseCode = "200",
            description = "Description of the addressed resource and request",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(type = "object"))
        )
    )
    @SneakyThrows
    @Override
    public void doGet(
        @Parameter(hidden = true)
        SlingJakartaHttpServletRequest request,
        @Parameter(hidden = true)
        @NonNull SlingJakartaHttpServletResponse response
    ) {
        log.info("Received GET request: {}", request.getRequestPathInfo());
        write(response, describe(request));
    }

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(
        summary = "Echo the posted parameters",
        description = "Reads the request parameters submitted with the POST request and echoes them back "
            + "as a JSON object",
        parameters = @Parameter(
            name = "resourcePath",
            in = ParameterIn.PATH,
            required = true,
            description = "Path of the addressed JCR resource",
            schema = @Schema(type = "string")
        )
    )
    @ApiResponses(
        @ApiResponse(
            responseCode = "200",
            description = "Posted parameters echoed back",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(type = "object"))
        )
    )
    @SneakyThrows
    @Override
    public void doPost(
        @Parameter(hidden = true)
        SlingJakartaHttpServletRequest request,
        @Parameter(hidden = true)
        @NonNull SlingJakartaHttpServletResponse response
    ) {
        log.info("Received POST request: {}", request.getRequestPathInfo());
        Map<String, Object> payload = new LinkedHashMap<>();
        request.getParameterMap()
            .forEach((paramName, paramValues) -> payload.put(paramName, String.join(",", paramValues)));
        write(response, payload);
    }

    private Map<String, Object> describe(SlingJakartaHttpServletRequest request) {
        RequestPathInfo requestPathInfo = request.getRequestPathInfo();
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("resourcePath", request.getResource().getPath());
        payload.put("selectors", Optional.ofNullable(requestPathInfo.getSelectorString()).orElse(""));
        payload.put("extension", Optional.ofNullable(requestPathInfo.getExtension()).orElse(""));
        payload.put("queryString", Optional.ofNullable(request.getQueryString()).orElse(""));
        payload.put("method", request.getMethod());
        return payload;
    }

    @SneakyThrows
    private void write(ServletResponse response, Map<String, Object> payload) {
        String json = new ObjectMapper().writeValueAsString(payload);
        response.setContentType(MediaType.APPLICATION_JSON);
        try (Writer responseWriter = response.getWriter()) {
            responseWriter.write(json);
        }
        log.info("Finished writing response");
    }
}
